sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - secure: VXmr4fnrKmPy1uka3KdLs8eaN1ReRE6xB/+hW22MckffwHtxO588rLEEJe6lAXPYYyzrwgIDDddWehcajTy2TBmYHnE2oOIK/dVleODoY/KCjhlAttFL92eT5ktVvq+v0NVEJ7szMigjSc2B/g1Qv9wNrudc3npQgp07TsP7rkAKZwaA4X0bYVlrUPIORKzJteZad4GwrpoUwYj+b3dw9lTegjti03AMRFhHzSdLmZnKRJY1147qrVoUdAiY0ati0IhIycx+CcpMV8UBKbVzvq9KEEqzPGzUR+eVE3karkZzGJl+p7LMs5vHHxWnxM1TXozXEWFsuGQM8cjFTnVedVZWY0q0f085s2jml8PDUzHYWfL7D7mE33csc9c/YTh7RvrjMbSFqRSTGmPcnj4SlXIz3ovnecDugPvlVurxoHAlBtCw9vd65DZbiVUF6YvPZLTdjlXZoVKiYManISo5OIr6wgIJ4xlqv3KPBtqUev8xfo0OXJT5+mcpBD+ePP7sLb9EDpANjj5a0IPu1L2yzch6LUrL5AMBDyYe/eJarUox7Hv09xUJQaSwI04upr5614Su4io1eZ0MXAFRV2KrKUIbjkVOVDlAVkDpGHKYTjxpjT1WfP3RQuw0n91O6MqwdDn/D4qfD4yhEvU4IUepPlZsn6HTDjxVKovnBz01KdM=
branches:
  only:
  - master
