# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-uk'

# Website info
m_name: 'UMBrain :: Into the Brain of taBRis.'
name: 'Into the Brain of taBRis'
description: "Memory Repository."

# Menu Info
menu_1: Security
menu_2: Unclassified

# Author's info
author: 'taBRis'
# edit 'categories' in the front matter of every post to match this username
nickname: tabris
bio: 'Into the Brain of taBRis.'
# location: 'Unknown'
url: 'http://tabriz83.github.io/umbrain/'
image: 'assets/images/author_ico.png'
fav_image: 'assets/images/Favicon.png'

short_url: 'tabriz83.github.io/umbrain/'
google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /umbrain/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# Markdown Processors
redcarpet: 
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "autolink", "underline", "highlight", "footnotes"]
 
# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: tabriz83
repo: umbrain
branch: master
relative_source: ../umbrain/
destination: ../umbrain-test/
production_url:  https://tabriz83.github.io/umbrain/
source_url:      https://github.com/tabriz83/umbrain/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
